---
- name: Set variables for this iteration of the loop.
  ansible.builtin.set_fact:
    manifest_directory: "{{ k8s_manifests_base_dir }}{{ k8s_manifests_component.dir | default(k8s_manifests_component) }}"
    manifest_lookup_type: "{{ k8s_manifests_component.lookup_type | default('template') }}"
    manifest_namespace: "{{ k8s_manifests_component.namespace | default('') }}"

- name: Print current manifest directory.
  ansible.builtin.debug:
    var: manifest_directory

- name: Ensure manifest-specific namespace exists.
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ manifest_namespace }}"
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
  when: manifest_namespace | default(false)

- name: Include vars specific to this manifest.
  ansible.builtin.include_vars: "{{ k8s_manifests_var }}"
  with_first_found:
    - files:
        - "{{ manifest_directory }}/vars.yml"
      skip: true
  loop_control:
    loop_var: k8s_manifests_var

- name: Deploy the resources defined inside the manifest.
  kubernetes.core.k8s:
    definition: "{{ k8s_manifests_definition }}"
    kubeconfig: "{{ k8s_kubeconfig }}"
    state: "{{ k8s_manifests_state }}"
    force: "{{ k8s_force }}"
  loop: "{{ lookup(manifest_lookup_type, manifest_directory + '/manifest.yml') | from_yaml_all | list }}"
  loop_control:
    loop_var: k8s_manifests_definition
  register: k8s_result
  until: k8s_result is success
  retries: 10
  delay: 2
  no_log: "{{ k8s_no_log }}"
